[global_shaders]
raygen = "path.rgen"
miss = "black.rmiss"
emitter_hit = "emitter.rchit"
directional_emitter_int = "disc.rint"
directional_emitter_hit = "directional_emitter.rchit"

[camera]
view = '''
lookat 0 2 2.2   0 0 2.2    0 0 1
'''
fov = 70

# area light
[[light]]
type = "area"
color = [1, 1, 1]
mesh = "square.obj"
transform = '''
rotate 180 0 1 0
scale 0.18 0.18 1
translate -0.8 0 3.8
translate 0 0 -2
rotate -90 0 1 0
translate 0 0 2
'''
emit_type = 1

#[[light]]
#type = "area"
#color = [200, 200, 200]
#mesh = "circle.obj"
#transform = '''
#rotate -90 1 0 0
#rotate -1 0 1 0
#scale 0.04 0.04 1
#translate 0.26 0.03 3
#translate 0 0 -2
#rotate -90 0 1 0
#translate 0 0 2
#'''
#emit_type = 0

[[light]]
type = "directional"
color = [80, 80, 80]
position = [-1, 0.045, 2.26]
direction = [2, 0, 0.6]
radius = 0.05

[[brdf]]
name = "diffuse"
chit_shader = "diffuse.rchit"
[[brdf.field]]
name = "albedo"
type = "vec3"

[[brdf]]
name = "dielectric"
chit_shader = "dielectric.rchit"
[[brdf.field]]
name = "b"
type = "vec3"
[[brdf.field]]
name = "c"
type = "vec3"

[[object]]
mesh = "triangle.obj"
transform = '''
rotate 30 0 1 0
translate 0 0 2.1
scale 1 0.7 1
translate 0 0 -2
rotate -90 0 1 0
translate 0 0 2
'''
brdf = {name = "dielectric", fields = [[1.03961212, 0.231792344, 1.01046945], [0.00600069867, 0.0200179144, 10.3560653]]}

# floor
[[object]]
mesh = "square.obj"
transform = '''
translate -.5 -.5 1
scale 5 1.5 1
translate 0 0 -2
rotate -90 0 1 0
translate 0 0 2
'''
brdf = {name = "diffuse", fields = [[0.9, 0.9, 0.9]]}

## new floor
#[[object]]
#mesh = "square.obj"
#transform = '''
#translate -.5 -.5 1
#scale 5 3 1
#'''
#brdf = {name = "diffuse", fields = [[1, 1, 1]]}

## new other floor
#[[object]]
#mesh = "square.obj"
#transform = '''
#translate -.5 -.5 1
#scale 5 3 1
#translate 0 0 -2
#rotate 90 0 1 0
#translate -1 0 2
#'''
#brdf = {name = "diffuse", fields = [[1, 1, 1]]}


# back wall
[[object]]
mesh = "square.obj"
transform = '''
rotate -90 1 0 0
translate -0.5 0.0 1
scale 5 10 5
'''
brdf = {name = "diffuse", fields = [[0.9, 0.9, 0.9]]}
