[global_shaders]
raygen = "path.rgen"
miss = "black.rmiss"
emitter_hit = "emitter.rchit"
directional_emitter_int = "disc.rint"
directional_emitter_hit = "directional_emitter.rchit"

[camera]
view = '''
lookat 0 2 2.2   0 0 2.2    0 0 1
'''
fov = 70

# area light
[[light]]
type = "area"
color = [0.05, 0.05, 0.05]
mesh = "square.obj"
transform = '''
rotate 180 0 1 0
scale 0.18 0.18 1
translate -0.8 0 3.8
translate 0 0 -2
rotate -90 0 1 0
translate 0 0 2
'''
emit_type = 1
spectra = "d65"

[[light]]
type = "directional"
color = [400, 400, 400]
position = [-4, 0.045, 0.00]
direction = [2, 0, 1.35]
radius = 0.05

[[brdf]]
name = "diffuse"
chit_shader = "diffuse.rchit"
[[brdf.field]]
name = "albedo"
type = "vec3"

[[brdf]]
name = "dielectric"
chit_shader = "dielectric.rchit"
[[brdf.field]]
name = "b"
type = "vec3"
[[brdf.field]]
name = "c"
type = "vec3"

[[object]]
mesh = "triangle.obj"
transform = '''
rotate 30 0 1 0
translate 0 0 2.1
scale 1 0.7 1
translate 0 0 -2
rotate -90 0 1 0
translate 0 0 2
'''
brdf = {name = "dielectric", fields = [[1.73759695, 0.313747346, 1.89878101], [0.013188707, 0.0623068142, 155.23629]]}

# floor
[[object]]
mesh = "square.obj"
transform = '''
translate -.5 -.5 1
scale 5 1.5 1
translate 0 0 -2
rotate -90 0 1 0
translate 0 0 2
'''
brdf = {name = "diffuse", fields = [[1, 1, 1]]}

# back wall
[[object]]
mesh = "square.obj"
transform = '''
rotate -90 1 0 0
translate -0.5 0.0 1
scale 5 10 5
'''
brdf = {name = "diffuse", fields = [[1, 1, 1]]}
